# Automatically generated by configure
# Configured with: './configure' '--platform=miyoo'
CC = /opt/miyoo-toolchain/bin/arm-buildroot-linux-musleabi-gcc
CXX = /opt/miyoo-toolchain/bin/arm-buildroot-linux-musleabi-g++
AS = /opt/miyoo-toolchain/bin/arm-buildroot-linux-musleabi-as
STRIP = /opt/miyoo-toolchain/bin/arm-buildroot-linux-musleabi-strip
CFLAGS +=  -marm -I/opt/miyoo-toolchain/arm-buildroot-linux-musleabi/sysroot/usr/bin/../../usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
ASFLAGS += 
LDFLAGS += 
LDLIBS += -L/opt/miyoo-toolchain/arm-buildroot-linux-musleabi/sysroot/usr/bin/../../usr/lib -lSDL -lpthread -lm -lasound -lm -ldl -lpthread -lpthread -ldl -lpng  -lm -lz

ARCH = arm
PLATFORM = miyoo
SOUND_DRIVERS = sdl
HAVE_LIBAVCODEC = 1
